#!/bin/bash
# Prestart script for traefik-container
# Creates acme.json and sets up dynamic middleware directory
set -e

# Derive package name from script location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_NAME="$(basename "$SCRIPT_DIR")"
ETC_DIR="/etc/container-apps/${PACKAGE_NAME}"

# Load config values from env files
set -a
[ -f "${ETC_DIR}/env.defaults" ] && . "${ETC_DIR}/env.defaults"
[ -f "${ETC_DIR}/env" ] && . "${ETC_DIR}/env"
set +a

# Create data directory
mkdir -p "${CONTAINER_DATA_ROOT}"

# Create acme.json with proper permissions if it doesn't exist
# Traefik requires this file to have 600 permissions
ACME_FILE="${CONTAINER_DATA_ROOT}/acme.json"
if [ ! -f "${ACME_FILE}" ]; then
    touch "${ACME_FILE}"
    chmod 600 "${ACME_FILE}"
fi

# ============================================
# Self-Signed TLS Certificate Generation
# ============================================
# Generate persistent self-signed certificate for HTTPS
# Certificate is regenerated if hostname changes

# Get HALOS_DOMAIN (same logic as generate-routing-labels.sh)
if [ -z "${HALOS_DOMAIN}" ]; then
    HOSTNAME="$(hostname -s)"
    HALOS_DOMAIN="${HOSTNAME}.local"
fi

CERTS_DIR="${CONTAINER_DATA_ROOT}/certs"
CERT_FILE="${CERTS_DIR}/halos.crt"
KEY_FILE="${CERTS_DIR}/halos.key"
DOMAIN_FILE="${CERTS_DIR}/.domain"

mkdir -p "${CERTS_DIR}"

# Check if certificate needs to be (re)generated
NEED_CERT=false
if [ ! -f "${CERT_FILE}" ] || [ ! -f "${KEY_FILE}" ]; then
    echo "Certificate files not found, generating..."
    NEED_CERT=true
elif [ -f "${DOMAIN_FILE}" ]; then
    STORED_DOMAIN=$(cat "${DOMAIN_FILE}")
    if [ "${STORED_DOMAIN}" != "${HALOS_DOMAIN}" ]; then
        echo "Domain changed from ${STORED_DOMAIN} to ${HALOS_DOMAIN}, regenerating certificate..."
        NEED_CERT=true
    fi
else
    # Domain file doesn't exist but certs do - regenerate to ensure consistency
    echo "Domain tracking file not found, regenerating certificate..."
    NEED_CERT=true
fi

if [ "${NEED_CERT}" = true ]; then
    echo "Generating self-signed TLS certificate for ${HALOS_DOMAIN}..."

    # Generate certificate with SAN for hostname and wildcard
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
        -keyout "${KEY_FILE}" \
        -out "${CERT_FILE}" \
        -subj "/CN=${HALOS_DOMAIN}" \
        -addext "subjectAltName=DNS:${HALOS_DOMAIN},DNS:*.${HALOS_DOMAIN}"

    chmod 600 "${KEY_FILE}"
    chmod 644 "${CERT_FILE}"

    # Store the domain for future comparison
    echo "${HALOS_DOMAIN}" > "${DOMAIN_FILE}"

    echo "Certificate generated successfully for ${HALOS_DOMAIN}"
else
    echo "Using existing certificate for ${HALOS_DOMAIN}"
fi

# Generate dynamic TLS configuration for Traefik
# This tells Traefik to use our persistent certificate as the default
TLS_CONFIG_FILE="/etc/halos/traefik-dynamic.d/tls-default.yml"
mkdir -p "$(dirname "${TLS_CONFIG_FILE}")"

cat > "${TLS_CONFIG_FILE}" << EOF
# Default TLS certificate configuration
# Auto-generated by Traefik prestart.sh
# Domain: ${HALOS_DOMAIN}

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/halos.crt
        keyFile: /certs/halos.key
EOF

chmod 644 "${TLS_CONFIG_FILE}"
echo "TLS configuration written to ${TLS_CONFIG_FILE}"

# ============================================
# Dynamic Configuration Directory
# ============================================
# This directory allows per-app middleware configurations
# Apps can drop their own middleware files here
DYNAMIC_DIR="/etc/halos/traefik-dynamic.d"
mkdir -p "${DYNAMIC_DIR}"

# Install default Authelia ForwardAuth middleware if not present
# This is the standard middleware for apps using forward_auth
AUTHELIA_MIDDLEWARE="${DYNAMIC_DIR}/authelia.yml"
AUTHELIA_MIDDLEWARE_SRC="${SCRIPT_DIR}/dynamic/authelia.yml"

if [ ! -f "${AUTHELIA_MIDDLEWARE}" ]; then
    if [ -f "${AUTHELIA_MIDDLEWARE_SRC}" ]; then
        echo "Installing default Authelia ForwardAuth middleware..."
        cp "${AUTHELIA_MIDDLEWARE_SRC}" "${AUTHELIA_MIDDLEWARE}"
        chmod 644 "${AUTHELIA_MIDDLEWARE}"
    else
        echo "WARNING: Default Authelia middleware not found at ${AUTHELIA_MIDDLEWARE_SRC}"
    fi
else
    echo "Authelia middleware already exists at ${AUTHELIA_MIDDLEWARE}"
fi

# ============================================
# Runtime Routing Label Generation
# ============================================
# Generate Traefik labels from generic routing declarations
# This reads /etc/halos/routing.d/*.yml and generates:
# - Docker-compose override files in /run/halos/routing-labels/
# - Per-app ForwardAuth middleware in /etc/halos/traefik-dynamic.d/
ROUTING_GENERATOR="${SCRIPT_DIR}/generate-routing-labels.sh"

if [ -f "${ROUTING_GENERATOR}" ]; then
    echo "Generating routing labels from /etc/halos/routing.d/..."
    # Export HALOS_DOMAIN for the generator script
    export HALOS_DOMAIN
    bash "${ROUTING_GENERATOR}"
else
    echo "WARNING: Routing generator not found at ${ROUTING_GENERATOR}"
fi

echo "Traefik prestart complete"
