#!/bin/bash
# Prestart script for traefik-container
# Creates acme.json and sets up dynamic middleware directory
set -e

# Derive package name from script location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_NAME="$(basename "$SCRIPT_DIR")"
ETC_DIR="/etc/container-apps/${PACKAGE_NAME}"

# Load config values from env files
set -a
[ -f "${ETC_DIR}/env.defaults" ] && . "${ETC_DIR}/env.defaults"
[ -f "${ETC_DIR}/env" ] && . "${ETC_DIR}/env"
set +a

# Create data directory
mkdir -p "${CONTAINER_DATA_ROOT}"

# Create acme.json with proper permissions if it doesn't exist
# Traefik requires this file to have 600 permissions
ACME_FILE="${CONTAINER_DATA_ROOT}/acme.json"
if [ ! -f "${ACME_FILE}" ]; then
    touch "${ACME_FILE}"
    chmod 600 "${ACME_FILE}"
fi

# ============================================
# Self-Signed TLS Certificate Generation
# ============================================
# Generate persistent self-signed certificate for HTTPS
# Certificate is regenerated if hostname changes

# Get HALOS_DOMAIN (same logic as generate-routing-labels.sh)
if [ -z "${HALOS_DOMAIN}" ]; then
    HOSTNAME="$(hostname -s)"
    HALOS_DOMAIN="${HOSTNAME}.local"
fi

# Write HALOS_DOMAIN to runtime.env for docker-compose label substitution
RUNTIME_ENV_DIR="/run/container-apps/${PACKAGE_NAME}"
mkdir -p "${RUNTIME_ENV_DIR}"
echo "HALOS_DOMAIN=${HALOS_DOMAIN}" >> "${RUNTIME_ENV_DIR}/runtime.env"

CERTS_DIR="${CONTAINER_DATA_ROOT}/certs"
CERT_FILE="${CERTS_DIR}/halos.crt"
KEY_FILE="${CERTS_DIR}/halos.key"
DOMAIN_FILE="${CERTS_DIR}/.domain"

mkdir -p "${CERTS_DIR}"

# Check if certificate needs to be (re)generated
NEED_CERT=false
if [ ! -f "${CERT_FILE}" ] || [ ! -f "${KEY_FILE}" ]; then
    echo "Certificate files not found, generating..."
    NEED_CERT=true
elif [ -f "${DOMAIN_FILE}" ]; then
    STORED_DOMAIN=$(cat "${DOMAIN_FILE}")
    if [ "${STORED_DOMAIN}" != "${HALOS_DOMAIN}" ]; then
        echo "Domain changed from ${STORED_DOMAIN} to ${HALOS_DOMAIN}, regenerating certificate..."
        NEED_CERT=true
    fi
else
    # Domain file doesn't exist but certs do - regenerate to ensure consistency
    echo "Domain tracking file not found, regenerating certificate..."
    NEED_CERT=true
fi

if [ "${NEED_CERT}" = true ]; then
    echo "Generating self-signed TLS certificate for ${HALOS_DOMAIN}..."

    # Generate certificate with SAN for hostname and wildcard
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
        -keyout "${KEY_FILE}" \
        -out "${CERT_FILE}" \
        -subj "/CN=${HALOS_DOMAIN}" \
        -addext "subjectAltName=DNS:${HALOS_DOMAIN},DNS:*.${HALOS_DOMAIN}"

    chmod 600 "${KEY_FILE}"
    chmod 644 "${CERT_FILE}"

    # Store the domain for future comparison
    echo "${HALOS_DOMAIN}" > "${DOMAIN_FILE}"

    echo "Certificate generated successfully for ${HALOS_DOMAIN}"
else
    echo "Using existing certificate for ${HALOS_DOMAIN}"
fi

# Generate dynamic TLS configuration for Traefik
# This tells Traefik to use our persistent certificate as the default
TLS_CONFIG_FILE="/etc/halos/traefik-dynamic.d/tls-default.yml"
mkdir -p "$(dirname "${TLS_CONFIG_FILE}")"

cat > "${TLS_CONFIG_FILE}" << EOF
# Default TLS certificate configuration
# Auto-generated by Traefik prestart.sh
# Domain: ${HALOS_DOMAIN}

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/halos.crt
        keyFile: /certs/halos.key
EOF

chmod 644 "${TLS_CONFIG_FILE}"
echo "TLS configuration written to ${TLS_CONFIG_FILE}"

# ============================================
# Cockpit Routing Configuration
# ============================================
# Generate Traefik routing for Cockpit (native systemd service)
# Cockpit runs on port 9090 and uses its own PAM authentication
COCKPIT_CONFIG_FILE="/etc/halos/traefik-dynamic.d/cockpit.yml"

cat > "${COCKPIT_CONFIG_FILE}" << EOF
# Cockpit routing configuration
# Auto-generated by Traefik prestart.sh
# Routes cockpit.${HALOS_DOMAIN} to the native Cockpit service
# Auth: none (Cockpit uses PAM authentication)

http:
  routers:
    cockpit:
      rule: "Host(\`cockpit.${HALOS_DOMAIN}\`)"
      entrypoints:
        - web
      middlewares:
        - redirect-to-https
      service: cockpit

    cockpit-secure:
      rule: "Host(\`cockpit.${HALOS_DOMAIN}\`)"
      entrypoints:
        - websecure
      tls: {}
      service: cockpit

  services:
    cockpit:
      loadBalancer:
        serversTransport: cockpit-transport
        servers:
          - url: "https://host.docker.internal:9090"

  serversTransports:
    cockpit-transport:
      insecureSkipVerify: true
EOF

chmod 644 "${COCKPIT_CONFIG_FILE}"
echo "Cockpit routing configuration written to ${COCKPIT_CONFIG_FILE}"

# ============================================
# Dynamic Configuration Directory
# ============================================
# This directory allows per-app middleware configurations
# Apps can drop their own middleware files here
DYNAMIC_DIR="/etc/halos/traefik-dynamic.d"
DYNAMIC_SRC_DIR="${SCRIPT_DIR}/assets/dynamic"
mkdir -p "${DYNAMIC_DIR}"

# Install all dynamic config files from package
# These include: authelia.yml, redirects.yml, insecure-transport.yml
if [ -d "${DYNAMIC_SRC_DIR}" ]; then
    for src_file in "${DYNAMIC_SRC_DIR}"/*.yml; do
        if [ -f "${src_file}" ]; then
            filename=$(basename "${src_file}")
            dest_file="${DYNAMIC_DIR}/${filename}"
            if [ ! -f "${dest_file}" ]; then
                echo "Installing dynamic config: ${filename}"
                cp "${src_file}" "${dest_file}"
                chmod 644 "${dest_file}"
            else
                echo "Dynamic config already exists: ${filename}"
            fi
        fi
    done
else
    echo "WARNING: Dynamic config source directory not found at ${DYNAMIC_SRC_DIR}"
fi

# ============================================
# Localhost Redirect Configuration
# ============================================
# Redirects http://*.localhost/ to https://*.${HALOS_DOMAIN}/
# This allows accessing services via subdomain.localhost on the device itself
LOCALHOST_REDIRECT_FILE="${DYNAMIC_DIR}/localhost-redirect.yml"

cat > "${LOCALHOST_REDIRECT_FILE}" << EOF
# Localhost to mDNS redirect
# Redirects http://*.localhost/ to https://*.${HALOS_DOMAIN}/
# Auto-generated by Traefik prestart.sh

http:
  routers:
    localhost-redirect:
      rule: "HostRegexp(\`{subdomain:[a-z0-9-]+}.localhost\`)"
      entrypoints:
        - web
      middlewares:
        - localhost-to-mdns
      # noop@internal is a valid but undocumented Traefik internal service.
      # It's the standard pattern for routers where middleware handles the
      # response (redirects never reach the backend). See:
      # https://github.com/traefik/traefik/issues/7291
      service: noop@internal
      priority: 1000

  middlewares:
    localhost-to-mdns:
      redirectRegex:
        regex: "^https?://([^.]+)\\\\.localhost(.*)"
        replacement: "https://\${1}.${HALOS_DOMAIN}\${2}"
        permanent: false
EOF

chmod 644 "${LOCALHOST_REDIRECT_FILE}"
echo "Localhost redirect configuration written to ${LOCALHOST_REDIRECT_FILE}"

echo "Traefik prestart complete"
